//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceImperialSoap")]
    public interface WebServiceImperialSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceClient.ServiceReference2.HelloWorldResponse HelloWorld(WebServiceClient.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.HelloWorldResponse> HelloWorldAsync(WebServiceClient.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TestConnectionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConnection", ReplyAction="*")]
        WebServiceClient.ServiceReference2.TestConnectionResponse TestConnection(WebServiceClient.ServiceReference2.TestConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.TestConnectionResponse> TestConnectionAsync(WebServiceClient.ServiceReference2.TestConnectionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento total del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        WebServiceClient.ServiceReference2.FindResponse Find(WebServiceClient.ServiceReference2.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.FindResponse> FindAsync(WebServiceClient.ServiceReference2.FindRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceClient.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceClient.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConnection", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.TestConnectionRequestBody Body;
        
        public TestConnectionRequest() {
        }
        
        public TestConnectionRequest(WebServiceClient.ServiceReference2.TestConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConnectionRequestBody {
        
        public TestConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.TestConnectionResponseBody Body;
        
        public TestConnectionResponse() {
        }
        
        public TestConnectionResponse(WebServiceClient.ServiceReference2.TestConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConnectionResult;
        
        public TestConnectionResponseBody() {
        }
        
        public TestConnectionResponseBody(string TestConnectionResult) {
            this.TestConnectionResult = TestConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(WebServiceClient.ServiceReference2.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string total;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(string total) {
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference2.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(WebServiceClient.ServiceReference2.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(string FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceImperialSoapChannel : WebServiceClient.ServiceReference2.WebServiceImperialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceImperialSoapClient : System.ServiceModel.ClientBase<WebServiceClient.ServiceReference2.WebServiceImperialSoap>, WebServiceClient.ServiceReference2.WebServiceImperialSoap {
        
        public WebServiceImperialSoapClient() {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference2.HelloWorldResponse WebServiceClient.ServiceReference2.WebServiceImperialSoap.HelloWorld(WebServiceClient.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceClient.ServiceReference2.HelloWorldRequest inValue = new WebServiceClient.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.HelloWorldRequestBody();
            WebServiceClient.ServiceReference2.HelloWorldResponse retVal = ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.HelloWorldResponse> WebServiceClient.ServiceReference2.WebServiceImperialSoap.HelloWorldAsync(WebServiceClient.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            WebServiceClient.ServiceReference2.HelloWorldRequest inValue = new WebServiceClient.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.HelloWorldRequestBody();
            return ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference2.TestConnectionResponse WebServiceClient.ServiceReference2.WebServiceImperialSoap.TestConnection(WebServiceClient.ServiceReference2.TestConnectionRequest request) {
            return base.Channel.TestConnection(request);
        }
        
        public string TestConnection() {
            WebServiceClient.ServiceReference2.TestConnectionRequest inValue = new WebServiceClient.ServiceReference2.TestConnectionRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.TestConnectionRequestBody();
            WebServiceClient.ServiceReference2.TestConnectionResponse retVal = ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).TestConnection(inValue);
            return retVal.Body.TestConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.TestConnectionResponse> WebServiceClient.ServiceReference2.WebServiceImperialSoap.TestConnectionAsync(WebServiceClient.ServiceReference2.TestConnectionRequest request) {
            return base.Channel.TestConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.TestConnectionResponse> TestConnectionAsync() {
            WebServiceClient.ServiceReference2.TestConnectionRequest inValue = new WebServiceClient.ServiceReference2.TestConnectionRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.TestConnectionRequestBody();
            return ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).TestConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference2.FindResponse WebServiceClient.ServiceReference2.WebServiceImperialSoap.Find(WebServiceClient.ServiceReference2.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public string Find(string total) {
            WebServiceClient.ServiceReference2.FindRequest inValue = new WebServiceClient.ServiceReference2.FindRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.FindRequestBody();
            inValue.Body.total = total;
            WebServiceClient.ServiceReference2.FindResponse retVal = ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.FindResponse> WebServiceClient.ServiceReference2.WebServiceImperialSoap.FindAsync(WebServiceClient.ServiceReference2.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference2.FindResponse> FindAsync(string total) {
            WebServiceClient.ServiceReference2.FindRequest inValue = new WebServiceClient.ServiceReference2.FindRequest();
            inValue.Body = new WebServiceClient.ServiceReference2.FindRequestBody();
            inValue.Body.total = total;
            return ((WebServiceClient.ServiceReference2.WebServiceImperialSoap)(this)).FindAsync(inValue);
        }
    }
}
